### ISSUE TITLE
ADICIONA STARTTYPING

### ISSUE THREAD

**Issue by c0dezinnn** [erla-team/erla#18]
ta tudo no nome

**Comment by NathaanScout** [comment]
Sua opnião é totalmente desnecessária. Você tem como prazer zoar com o repositórios dos outros. Por favor, se retirar do grupo?!!!


Contém humor.

**Comment by atshushi** [comment]
não tem slash commands ainda, portanto esta função ainda não pode ser implementada...

**Comment by 2vitor** [comment]
tenta [isso](https://discord.com/developers/docs/resources/channel#trigger-typing-indicator)
