### ISSUE TITLE
Websocket problem

### ISSUE THREAD

**Issue by drethenrain** [erla-team/erla#21]
![unknown](https://user-images.githubusercontent.com/76497268/132933509-04fa3df3-cb97-4ac8-a06b-7e1d47ed144f.png)

**Comment by loveviolinn** [comment]
The problem is in the unnecessary recursion of the `heartbeat` method of the WebSocketManager, we are working to fix that. Ty :3

**Comment by loveviolinn** [comment]
Fixed
